import { serverClient } from "@repo/provider";
import LayoutContext from "./LayoutContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { gql, ApolloClient, OperationVariables } from "@apollo/client";
import { cookies } from 'next/headers'


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

const query = gql` 
    query getProjects($id: ID!) {
    objects {
        getProjects(objectId: $id) {
            objectId
        }
    }
}`

 
interface GetProjectsResponse {
  objects: {
      getProjects: {
          objectId: string;
      };
  };
}

const getData = async () => {
  const projectId = cookies().get('cms_project')?.value || '123';
  console.log(process.env.SASHIDO_APP_ID);
  const client: ApolloClient<any> = serverClient(process.env.SASHIDO_API_URL as string, process.env.SASHIDO_APP_ID as string, process.env.SASHIDO_MASTER_KEY as string);

  console.log(projectId, 'projectId');
  
  const { data } = await client.query<GetProjectsResponse, OperationVariables>({ query, variables: { id: projectId } });

  return data;
}
 


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}){
  const data = await getData()
  console.log(data, 'pageData');
  return (
      <html lang="de">
        <body className={inter.className}>
            <h3>
                {data.objects.getProjects.objectId}
            </h3>
          <LayoutContext>
            {children}
          </LayoutContext>
          </body>
      </html>
  );
}
