import { serverClient } from "@repo/provider";
import LayoutContext from "./LayoutContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { gql } from "@apollo/client";
import { env } from "process";
import { on } from "events";

const inter = Inter({ subsets: ["latin"] });
import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

const query = gql` 
query findProjects {
  objects {
    findProjects {
      results {

        objectId
      }
    }
  }
}`

 
type Repo = {
  name: string
  stargazers_count: number
}
 
export const getServerSideProps = (async () => {
  console.log(process.env.SASHIDO_APP_ID);
  const client = serverClient(process.env.SASHIDO_APP_ID, process.env.SASHIDO_MASTER_KEY);

  const { data } = await client.query({ query }, {onError: (error) => console.log(error)});
  return { props: { data } }
})

export default function RootLayout({
  data,
  children,
}: {
  children: React.ReactNode;
}){
  console.log(data);
  

  return (
      <html lang="en">
        <body className={inter.className}>
          <LayoutContext>
            {children}
          </LayoutContext>
          </body>
      </html>
  );
}
